### ISSUE TITLE
NEED FOR HELP - NEW COLLABORATOR

### ISSUE THREAD

**Issue by juliandavidmr** [juliandavidmr/awesome-nestjs#134]
Hi everyone, NestJS is growing every day and there are a lot of new technologies for it. Many technologies come to awesome-nest, so I'm looking to someone who wants help to maintain this awesome GitHub repository. - _What I expect from the contributor?  - review PR, check new issues, must have experience working with NestJS._

Leave a comment below, describe why you want to be a contributor🥇.

**Comment by kitt3911** [comment]
Hi, I would really like to do this, since I am also interested in backend development on nest, and I want to contribute to the development of useful things
